/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package news;

/**
 * Imports section.
 */
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Generic implementation of an Graphical Interface with java swing.
 * 
 * Métodos Probabilísticos Para a Engenharia Informática.
 * 2018-2019.
 * Prática 4.
 * Professor: António Teixeira.
 * Alunos: Rui Coelho e Vitor Fajardo.
 */


public class NewsFrame extends javax.swing.JFrame {
    
    /**
     * Data information.
     */
    private final NewsData data;
    /**
     * Array of current news.
     */
    private News[] currentResults;
    /**
     * Array of similar news.
     */
    private News[] currentSimilar;
    /**
     * Current news.
     */
    private News current;

    /**
     * Create new frame.
     * 
     * The categories are given by the folder name placed on dataset/news.
     * 
     * He have 5 categories:
     *      - Tennis
     *      - Athletics
     *      - Cricket
     *      - Football
     *      - Rugby
     * 
     * There is other category called Any that displays all news.
     */
    
    public NewsFrame() {
        data = new NewsData("dataset/news");
        initComponents();
        CategoryList.add("Any");
        CategoryList.add("Tennis");
        CategoryList.add("Athletics");
        CategoryList.add("Cricket");
        CategoryList.add("Football");
        CategoryList.add("Rugby");
        SearchButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        News = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Content = new javax.swing.JTextArea();
        Title = new javax.swing.JTextField();
        Similar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SimilarList = new java.awt.List();
        Search = new javax.swing.JPanel();
        SearchInput = new java.awt.TextField();
        SearchButton = new java.awt.Button();
        SearchResuts = new java.awt.List();
        CategoryList = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setEditable(false);
        Content.setColumns(20);
        Content.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Content.setLineWrap(true);
        Content.setRows(5);
        Content.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Content);

        Title.setEditable(false);
        Title.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Title.setText("News");

        javax.swing.GroupLayout NewsLayout = new javax.swing.GroupLayout(News);
        News.setLayout(NewsLayout);
        NewsLayout.setHorizontalGroup(
            NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addComponent(Title))
                .addContainerGap())
        );
        NewsLayout.setVerticalGroup(
            NewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel1.setText("Similar news");

        SimilarList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SimilarListItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout SimilarLayout = new javax.swing.GroupLayout(Similar);
        Similar.setLayout(SimilarLayout);
        SimilarLayout.setHorizontalGroup(
            SimilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimilarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(SimilarLayout.createSequentialGroup()
                .addComponent(SimilarList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SimilarLayout.setVerticalGroup(
            SimilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimilarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SimilarList, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SearchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchInputKeyPressed(evt);
            }
        });

        SearchButton.setActionCommand("Search");
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SearchButton.setLabel("Search");
        SearchButton.setName("Search"); // NOI18N
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchResuts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SearchResutsItemStateChanged(evt);
            }
        });

        jLabel2.setText("Category");

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addComponent(SearchInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchResuts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CategoryList, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CategoryList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchResuts, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Similar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(News, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(News, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Similar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Function that search the information introduced by users.
     * 
     * @param evt 
     *          Event.
     */
    
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (evt == null)
        {
            SearchResuts.removeAll();
            String input = SearchInput.getText();
            String category = CategoryList.getSelectedItem().toLowerCase();
            List<News> result = data.search(category, input);
            currentResults = new News[result.size()];
            int cont = 0;
            for (News a : result) {
                SearchResuts.add(a.getTitle());
                currentResults[cont++] = a;
            }
        }
        else{
            String input = SearchInput.getText();
            if ("".equals(input)){
                System.out.println("Sem conteúdo!");
                Component empty= null;
                JOptionPane.showMessageDialog(empty, "Não é possível fazer pesquisa vazia.");
            }
            else{
                SearchResuts.removeAll();
                String category = CategoryList.getSelectedItem().toLowerCase();
                List<News> result = data.search(category, input);
                currentResults = new News[result.size()];
                int cont = 0;
                for (News a : result) {
                    SearchResuts.add(a.getTitle());
                    currentResults[cont++] = a;
                }
            }
        }
        
        
    }//GEN-LAST:event_SearchButtonActionPerformed
    
    /**
     * Display a list of similiar news.
     * 
     * @param evt 
     *          Event.
     */
    private void SimilarListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SimilarListItemStateChanged
        System.out.println("Similar Item pressed.");
        current = currentSimilar[Integer.parseInt(evt.getItem().toString())];
        displayNews(current);
    }//GEN-LAST:event_SimilarListItemStateChanged
    
    /**
     * Search for similiar news and display the clicked one.
     * 
     * @param evt 
     *          Event.
     */
    private void SearchResutsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SearchResutsItemStateChanged
        System.out.println("New searchs");
        current = currentResults[Integer.parseInt(evt.getItem().toString())];
        displayNews(current);
    }//GEN-LAST:event_SearchResutsItemStateChanged
    
    /**
     * Search for a news when the ENTER key is pressed.
     * 
     * @param evt 
     *          Event.
     */
    private void SearchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchInputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            System.out.println("ENTER key pressed");
            String input = SearchInput.getText();
            if ("".equals(input)){
                System.out.println("Sem conteúdo!");
                Component empty= null;
                JOptionPane.showMessageDialog(empty, "Não é possível fazer pesquisa vazia.");
            }
            else{
            SearchResuts.removeAll();
            String category = CategoryList.getSelectedItem().toLowerCase();
            List<News> result = data.search(category, input);
            currentResults = new News[result.size()];
            int cont = 0;
            for (Iterator<news.News> it = result.iterator(); it.hasNext();) {
                News a = it.next();
                SearchResuts.add(a.getTitle());
                currentResults[cont++] = a;
            }
            }
        }
    }//GEN-LAST:event_SearchInputKeyPressed
    
    
    /**
     * Change the displayed news and show similar ones.
     * 
     * @param current
     *         Current news.
     */
    private void displayNews(News current) {
        SimilarList.removeAll();
        Content.setText(current.getContent());
        Title.setText(current.getTitle());
        List<News> res = data.compare(current);
        currentSimilar = new News[res.size()];
        int cont = 0;
        for (Iterator<news.News> it = res.iterator(); it.hasNext();) {
            News r = it.next();
            currentSimilar[cont++] = r;
            SimilarList.add(r.getTitle());
        }
    }
    /**
     * Generate the interface.
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }
    
    /**
     * Generic Implemtation of Runnable Interface.
     */
    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            System.out.println("Início do formulário.");
            System.out.println("Abrindo Interface...");
            new NewsFrame().setVisible(true);
            System.out.println("Tudo pronto!");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice CategoryList;
    private javax.swing.JTextArea Content;
    private javax.swing.JPanel News;
    private javax.swing.JPanel Search;
    private java.awt.Button SearchButton;
    private java.awt.TextField SearchInput;
    private java.awt.List SearchResuts;
    private javax.swing.JPanel Similar;
    private java.awt.List SimilarList;
    private javax.swing.JTextField Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
